name: build-windows

on:
    push:
        branches: [ master, release/0.2 ]
    pull_request:
        branches: [ master, release/0.2 ]

jobs:
    build-windows:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-2022, windows-2019]
                swift: [5.6.2, 5.5.3, 5.4.3]
        steps:
            -   name: checkout 
                uses: actions/checkout@v2
            
            -   name: toolchain 
                uses: compnerd/gha-setup-swift@main
                with:
                    branch: swift-${{ matrix.swift }}-release
                    tag: ${{ matrix.swift }}-RELEASE
            -   name: build 
                run: | 
                    swift --version
                    swift build
