name: build-devices

on:
    push:
        branches: [ master, release/0.2 ]
    pull_request:
        branches: [ master, release/0.2 ]

jobs:
    devices:
        runs-on: ${{ matrix.os }}
        name: ${{ matrix.device }} (${{ matrix.os }}, ${{ matrix.swift }})
        strategy:
            matrix:
                os: [macos-12]
                device: [ios, tvos, watchos]
        steps:
            -   uses: actions/checkout@v2
            -   name: build 
                run: |
                    swift --version
                    xcrun xcodebuild build -scheme "swift-json" -destination "generic/platform=${{ matrix.device }}"
