name: build

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    macos:
        runs-on: ${{ matrix.os }}
        name: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    -   macos-14
        steps:
            -   name: Select Xcode
                uses: maxim-lobanov/setup-xcode@v1
                with:
                    xcode-version: '15.3.0'

            -   name: Checkout repository
            -   uses: actions/checkout@v3

            -   name: Run pipeline
                run: .github/pipeline

    linux:
        runs-on: ubuntu-22.04
        name: ${{ matrix.image }}

        strategy:
            matrix:
                image:
                -   tayloraswift/5.10.0-amazonlinux2023:latest
        steps:
            -   name: checkout repository
                uses: actions/checkout@v3

            -   name: build and test
                run: |
                    docker run -t --rm \
                        --name swift-environment \
                        --user root \
                        -v $PWD:/swift-json \
                        -w /swift-json \
                        ${{ matrix.image }} \
                        .github/pipeline
