name: build

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    macos:
        runs-on: macos-14
        name: macOS
        env:
            SWIFT_TOOLCHAIN_DIRECTORY: /Library/Developer/Toolchains/swift-${{ matrix.swift.toolchain }}.xctoolchain
            TOOLCHAINS: /Library/Developer/Toolchains/swift-${{ matrix.swift.toolchain }}.xctoolchain

        strategy:
            matrix:
                swift:
                    -   toolchain:  5.10-RELEASE
                        branch:     swift-5.10-release
        steps:
            -   name: cache swift toolchains
                uses: actions/cache@v2
                with:
                    path: swift-${{ matrix.swift.toolchain }}.pkg
                    key: macos:swift:${{ matrix.swift.toolchain }}

            -   name: cache status
                id:   cache_status
                uses: andstor/file-existence-action@v1
                with:
                    files: swift-${{ matrix.swift.toolchain }}.pkg

            -   name: download swift toolchain
                if: steps.cache_status.outputs.files_exists == 'false'
                run:   "curl https://download.swift.org/\
                        ${{ matrix.swift.branch }}/xcode/\
                        swift-${{ matrix.swift.toolchain }}/\
                        swift-${{ matrix.swift.toolchain }}-osx.pkg \
                        --output swift-${{ matrix.swift.toolchain }}.pkg"

            -   name: set up swift
                run: |
                    sudo installer -pkg swift-${{ matrix.swift.toolchain }}.pkg -target /

            -   name: Checkout repository
                uses: actions/checkout@v3

            # -   name: build
            #     run: |
            #         $SWIFT_TOOLCHAIN_DIRECTORY/usr/bin/swift --version
            #         $SWIFT_TOOLCHAIN_DIRECTORY/usr/bin/swift build

            -   name: Run pipeline
                run: .github/pipeline

    linux:
        runs-on: ubuntu-22.04
        name: ${{ matrix.image }}

        strategy:
            matrix:
                image:
                -   tayloraswift/5.10.0-amazonlinux2023:latest
        steps:
            -   name: checkout repository
                uses: actions/checkout@v3

            -   name: build and test
                run: |
                    docker run -t --rm \
                        --name swift-environment \
                        --user root \
                        -v $PWD:/swift-json \
                        -w /swift-json \
                        ${{ matrix.image }} \
                        .github/pipeline
