name: test

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    linux:
        runs-on: ubuntu-24.04
        name: Ubuntu 24.04
        steps:
            -   name: Install Swift
                uses: tayloraswift/swift-install-action@master
                with:
                    swift-prefix: "swift-6.0.1-release/ubuntu2404/swift-6.0.1-RELEASE"
                    swift-id: "swift-6.0.1-RELEASE-ubuntu24.04"

            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Run pipeline
                run: .github/pipeline

    macos:
        runs-on: macos-15
        name: macOS
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Run pipeline
                run: .github/pipeline

    devices:
        runs-on: macos-15
        name: macOS
        strategy:
            matrix:
                device: [ios, tvos, watchos]
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Build
                run: |
                    swift --version
                    xcrun xcodebuild -list
                    xcrun xcodebuild build \
                        -scheme "JSON" \
                        -destination "generic/platform=${{ matrix.device }}"
                    xcrun xcodebuild build \
                        -scheme "JSONLegacy" \
                        -destination "generic/platform=${{ matrix.device }}"

